### ISSUE TITLE
공공 데이터 api에서 가져온 데이터로 Eudcation Entity로 매핑하여 DB에 저장한다.

### ISSUE THREAD

**Issue by kwakmins** [seungjoo-ahn/seoul-competition-backend#14]
## 📝 Description

공공 데이터 api에서 가져온 데이터로 Eudcation Entity로 매핑하여 DB에 저장합니다.

## ☑️ TODO

- [x] FiftyApi를 가지고 Education Entity로 저장합니다.
- [x] SeniorApi를 가지고 Education Entity로 저장합니다.
- [x] 프로젝트가 시작하자마자 실행을 하게 해야합니다.
