### ISSUE TITLE
시각화API를 구현한다.

### ISSUE THREAD

**Issue by kwakmins** [seungjoo-ahn/seoul-competition-backend#140]
## 📝 Description

시각화를 위해 필요한 쿼리문을 모두 작성하는 API를 구현합니다.

## ☑️ TODO

- [x] 자유게시판 최다 조회 게시글 Top5
- [x] 교육 정보 최다 조회  게시글 Top5
- [x] 교육 정보 최다 검색 키워드 Top5
- [x] 관심사별 교육 정보 최다 조회 Top5
- [x] 연령대별 교육 정보 최다 검색 키워드 Top5
