### ISSUE TITLE
교육 정보 리스트의 페이지와 정렬 기능 구현한다.

### ISSUE THREAD

**Issue by kwakmins** [seungjoo-ahn/seoul-competition-backend#36]
## 📝 Description

설명을 작성하세요.

교육 정보 리스트의 페이지와 정렬 기능 구현합니다.

## ☑️ TODO

- [x] 교육 정보 리스트의 페이지 기능 구현
- [x] 교육 정보 리스트의 `state` 내림차순 정렬 기능 구현
- [x] 교육 정보 리스트 api 스팩에 총 페이지 수와, 현재 페이지를 구현
