### ISSUE TITLE
Swagger 설정을 한다.

### ISSUE THREAD

**Issue by seungjoo-ahn** [seungjoo-ahn/seoul-competition-backend#7]
## 📝 Description
협업을 위해 Swagger 설정을 한다.

## ☑️ TODO
 
- [ ] ~~gradle에 'io.springfox:springfox-boot-starter:3.0.0'를 추가한다.~~
- [x] gradle에 'io.org.springdoc:springdoc-openapi-starter-webmvc-ui:2.0.2'을 추가한다.
- [x] gradle에 'io.org.springframework.boot:spring-boot-starter-validation'을 추가한다.
- [x] SwaggerConfig를 생성하고 옵션을 추가해준다.
