### ISSUE TITLE
게시글 검색, 조회 기록을 저장하는 로직을 구현한다.

### ISSUE THREAD

**Issue by seungjoo-ahn** [seungjoo-ahn/seoul-competition-backend#86]
## 📝 Description
- 게시글 검색, 조회 기록을 저장하는 로직을 구현해야 합니다.
## ☑️ TODO
 

- [ ] jjwt 의존성 주입
- [ ] jwt로 암호화 후, 쿠키에 넣어서 주는 로직 구현
- [ ] 쿠키 유무 확인 후 검색 기록, 조회 기록 저장하는 로직 구현
