### ISSUE TITLE
교육 Entity의 colum 타입을 리팩토링 한다.

### ISSUE THREAD

**Issue by kwakmins** [seungjoo-ahn/seoul-competition-backend#95]
## 📝 Description

queryDsl로 동적 쿼리를 작성 도중, 외부 API로 가져온 컬럼이라 편하게 String으로 모두 지정했던 컬럼들로 인해서, 쿼리문 작성이 어려워 졌습니다.
애초에 모두 String으로 지정을 하면, 이런 문제 뿐만 아니라, 성능 저하도 생길 수 있어 리팩토링을 하는게 맞다는 판단을하였습니다.

하지만 프론트에선 똑같은 타입으로 받을 수 있게 하겠습니다.

## ☑️ TODO

- [x] price를 String -> Integer (DTO는 String ("###,###"))
- [x] capcity를 int -> Integer
- [x] 날짜 관련을 String -> LocalDate
